# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordInfoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 54)
        self.filepathLabel = QtWidgets.QLabel(Form)
        self.filepathLabel.setGeometry(QtCore.QRect(10, 30, 380, 12))
        self.filepathLabel.setObjectName("filepathLabel")
        self.timestrLabel = QtWidgets.QLabel(Form)
        self.timestrLabel.setGeometry(QtCore.QRect(10, 10, 70, 12))
        self.timestrLabel.setObjectName("timestrLabel")
        self.filesizeLabel = QtWidgets.QLabel(Form)
        self.filesizeLabel.setGeometry(QtCore.QRect(90, 10, 60, 12))
        self.filesizeLabel.setObjectName("filesizeLabel")
        self.bitrateLabel = QtWidgets.QLabel(Form)
        self.bitrateLabel.setGeometry(QtCore.QRect(160, 10, 90, 12))
        self.bitrateLabel.setObjectName("bitrateLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filepathLabel.setText(_translate("Form", "TextLabel"))
        self.timestrLabel.setText(_translate("Form", "00:00:00.00"))
        self.filesizeLabel.setText(_translate("Form", "0kb"))
        self.bitrateLabel.setText(_translate("Form", "0.0kbits/s"))
